//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flitter.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPic
    {
        public int ID { get; set; }
        public byte[] Pic { get; set; }
        public Nullable<int> ID_Product { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
