//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flitter.RESOURCES {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationLabels() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flitter.RESOURCES.ValidationLabels", typeof(ValidationLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adresse ähnelt.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sperrdatum ähnelt.
        /// </summary>
        public static string BANDATE {
            get {
                return ResourceManager.GetString("BANDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geburtstag ähnelt.
        /// </summary>
        public static string BIRTHDATE {
            get {
                return ResourceManager.GetString("BIRTHDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreditkartenfirma ähnelt.
        /// </summary>
        public static string CARD_COMPANY {
            get {
                return ResourceManager.GetString("CARD_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ablaufdatum ähnelt.
        /// </summary>
        public static string CARD_EXPIRY {
            get {
                return ResourceManager.GetString("CARD_EXPIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kartenbesitzer ähnelt.
        /// </summary>
        public static string CARD_HOLDER {
            get {
                return ResourceManager.GetString("CARD_HOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name der Karte ähnelt.
        /// </summary>
        public static string CARD_NAME {
            get {
                return ResourceManager.GetString("CARD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kartennummer ähnelt.
        /// </summary>
        public static string CARD_NUMBER {
            get {
                return ResourceManager.GetString("CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherheitscode ähnelt.
        /// </summary>
        public static string CARD_SECURITY_N {
            get {
                return ResourceManager.GetString("CARD_SECURITY_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stadt ähnelt.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firma ähnelt.
        /// </summary>
        public static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort bestätigen ähnelt.
        /// </summary>
        public static string CONFIRMATION {
            get {
                return ResourceManager.GetString("CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontostand ähnelt.
        /// </summary>
        public static string CURRENCYBALANCE {
            get {
                return ResourceManager.GetString("CURRENCYBALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emailadresse ähnelt.
        /// </summary>
        public static string EMAIL_LABEL {
            get {
                return ResourceManager.GetString("EMAIL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorname ähnelt.
        /// </summary>
        public static string FIRSTNAME {
            get {
                return ResourceManager.GetString("FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spitzname ähnelt.
        /// </summary>
        public static string GAMERTAG {
            get {
                return ResourceManager.GetString("GAMERTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identifikationsnummer ähnelt.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bild ähnelt.
        /// </summary>
        public static string IMAGE {
            get {
                return ResourceManager.GetString("IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiv(Hacken für gelöscht) ähnelt.
        /// </summary>
        public static string ISACTIVE {
            get {
                return ResourceManager.GetString("ISACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelöscht ähnelt.
        /// </summary>
        public static string ISDELETED {
            get {
                return ResourceManager.GetString("ISDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ist ein COIN-Packet? ähnelt.
        /// </summary>
        public static string ISMONEY {
            get {
                return ResourceManager.GetString("ISMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nachname ähnelt.
        /// </summary>
        public static string LASTNAME {
            get {
                return ResourceManager.GetString("LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl ähnelt.
        /// </summary>
        public static string NUMBER {
            get {
                return ResourceManager.GetString("NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort ähnelt.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preis ähnelt.
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierungsdatum ähnelt.
        /// </summary>
        public static string SIGN_IN_DATE {
            get {
                return ResourceManager.GetString("SIGN_IN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Habe die Agb´s durchgelesen und akzeptiere sie ähnelt.
        /// </summary>
        public static string TERMS_ACCEPT {
            get {
                return ResourceManager.GetString("TERMS_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summe ähnelt.
        /// </summary>
        public static string TOTAL_COST {
            get {
                return ResourceManager.GetString("TOTAL_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nick ähnelt.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolle ähnelt.
        /// </summary>
        public static string USERROLE {
            get {
                return ResourceManager.GetString("USERROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert ähnelt.
        /// </summary>
        public static string WORTH {
            get {
                return ResourceManager.GetString("WORTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Postleitzahl ähnelt.
        /// </summary>
        public static string ZIP {
            get {
                return ResourceManager.GetString("ZIP", resourceCulture);
            }
        }
    }
}
